# From what I can tell, this is working
# when passed into AWS CloudFormation, it creates a stack and
# all the VPC's and subnets work fine 

AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC: public and private subnets in two availability zones, a cloudonaut.io template'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
#    Properties:

  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  
  SubnetAPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-east-2a
      CidrBlock: '10.0.0.0/20' # THE HARD CODING CAN BE REMOVED
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  SubnetBPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-east-2b
      CidrBlock: '10.0.16.0/20'
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  SubnetCPublic:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-east-2c
      CidrBlock: '10.0.32.0/20'
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

Outputs:
  CidrBlock:
    Description: 'The set of IP addresses for the VPC.'
    Value: !GetAtt 'VPC.CidrBlock'
    Export:
      Name: !Sub 'teststack-CidrBlock'
  VPC:
    Description: 'VPC.'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC' # using stackname is fine 
  # SubnetsPublic:
    # Description: 'Subnets public.'
    # Value: !Join [',', [!Ref SubnetAPublic, !Ref SubnetBPublic], !Ref SubnetCPublic]
    # Export:
      # Name: !Sub '${AWS::StackName}-SubnetsPublic'
  SubnetAPublic: # why do we export the subnets as a group but also individually?
    Description: 'Subnet A public.'
    Value: !Ref SubnetAPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetAPublic'
  SubnetBPublic:
    Description: 'Subnet B public.'
    Value: !Ref SubnetBPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetBPublic'
  SubnetCPublic:
    Description: 'Subnet C public.'
    Value: !Ref SubnetCPublic
    Export:
      Name: !Sub '${AWS::StackName}-SubnetCPublic'
