
####    CODEDEPLOY    ####
# application, config, deployment group
DemoProjectCodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties: 
        ApplicationName: demoproject-codedeployapp
        ComputePlatform: ECS

#DemoProjectCodeDeployConfig:
#    Type: AWS::CodeDeploy::DeploymentConfig
#    Properties: 
#        DeploymentConfigName: String # I'll take the default
#        MinimumHealthyHosts: 
#        MinimumHealthyHosts
# can I just NOT have this 

DemoProjectDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: DemoProjectCodeDeployApp
    Properties: 
#        AlarmConfiguration: 
#            AlarmConfiguration
        ApplicationName: !Ref DemoProjectCodeDeployApp
        DeploymentConfigName: CodeDeployDefault.AllAtOnce
        DeploymentGroupName: demoproject-codedeploygroup
        DeploymentStyle: 
            DeploymentStyle !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            DeploymentStyle:
                DeploymentOption: WITH_TRAFFIC_CONTROL
        LoadBalancerInfo: 
            TargetGroupInfoList:
                Name: # depends on BG/IP
#        OnPremisesInstanceTagFilters: 
#            - TagFilter
#        OnPremisesTagSet: 
#            OnPremisesTagSet
        ServiceRoleArn: String !!!!!!!!!!!!!!!!!!
        TriggerConfigurations: 
           - TriggerConfig